package com.magmaguy.betterstructures.util;

import org.bukkit.Chunk;
import org.bukkit.Material;
import org.bukkit.World;

/**
 * Utility class for validating chunk generation state.
 * Provides compatibility checks for async world generators like Terra + FAWE,
 * where chunks may be loaded but not yet fully populated with terrain data.
 */
public class ChunkValidationUtil {

    private ChunkValidationUtil() {
        // Utility class - no instantiation
    }

    /**
     * Checks whether a chunk has been fully generated by sampling multiple positions
     * to detect empty or partially generated chunks.
     *
     * @param chunk the chunk to validate
     * @return true if the chunk appears fully generated, false if null, unloaded, or incomplete
     */
    public static boolean isChunkFullyGenerated(Chunk chunk) {
        if (chunk == null || !chunk.isLoaded()) return false;

        try {
            World world = chunk.getWorld();
            int baseX = chunk.getX() << 4;
            int baseZ = chunk.getZ() << 4;

            // Sample 4 positions: center and edges
            int[][] offsets = {
                    {0, 7},
                    {7, 0},
                    {15, 7},
                    {7, 15}
            };

            int airOnlyColumns = 0;
            int voidAirCount = 0;

            for (int[] offset : offsets) {
                int x = baseX + offset[0];
                int z = baseZ + offset[1];
                int highestY = world.getHighestBlockYAt(x, z);

                if (highestY <= world.getMinHeight()) {
                    airOnlyColumns++;
                }

                // Use sea level or mid-point as reference height (adapts to different world types)
                int checkY = (world.getMaxHeight() + world.getMinHeight()) / 2;
                if (world.getBlockAt(x, checkY, z).getType() == Material.VOID_AIR) {
                    voidAirCount++;
                }
            }

            if (airOnlyColumns >= 3 || voidAirCount >= 2) {
                return false;
            }

            return true;
        } catch (Exception e) {
            // Don't block structure placement on validation errors
            return true;
        }
    }

    /**
     * Checks if a chunk has reached ENTITY_TICKING load level (fully ready).
     * This is the highest load level, meaning the chunk is fully loaded,
     * all neighbors are loaded, and entities can tick.
     *
     * This provides better compatibility with FAWE and async world generators
     * by ensuring the chunk is completely ready before structure placement.
     *
     * @param chunk the chunk to check
     * @return true if the chunk is at ENTITY_TICKING level, false otherwise
     */
    public static boolean isChunkFullyReady(Chunk chunk) {
        if (chunk == null || !chunk.isLoaded()) return false;

        try {
            // Paper API: Check if chunk has reached the highest load level
            // ENTITY_TICKING means chunk is fully loaded with all neighbors ready
            return chunk.getLoadLevel() == Chunk.LoadLevel.ENTITY_TICKING;
        } catch (NoSuchMethodError | NoClassDefFoundError e) {
            // Fallback for non-Paper servers: use basic generation check
            return isChunkFullyGenerated(chunk);
        }
    }

}
